import {SelfWritingJson} from "./selfWritingJson";
import {paxiDatapacksPath} from "./utils";

export class PackMcMeta extends SelfWritingJson {
    static outputPath = "pack.mcmeta";
    pack = {
        pack_format: 9,
        description: "Expansion Pack autogenerated by Zoompack"
    }
    isPaxiMeta = false;

    constructor(rootPath: string, namespace: string) {
        super(rootPath, namespace, PackMcMeta.outputPath);
    }

    withDescription(description: string) {
        this.pack.description = description;
        return this;
    }

    withPackFormat(format: number) {
        this.pack.pack_format = format;
        return this;
    }

    override validate() {
        if (this.internalNamespace === SelfWritingJson.AUTO_FILL || this.internalNamespace === "") {
            throw new Error("[NAMESPACE] Cannot write autofilled json, " + this.filePath);
        }
    }

    override cleanBeforeWrite() {
        super.cleanBeforeWrite();
        this.isPaxiMeta = undefined;
    }

    override updateFilePath() {
        if (this.isPaxiMeta) {
            this.filePath = `${paxiDatapacksPath()}/${this.internalNamespace}/${this.template.replace("<internalNamespace>", this.internalNamespace).replace("<internalName>", this.internalName)}`;
        } else {
            super.updateFilePath();
        }
    }

    isPaxiPackMeta() {
        this.isPaxiMeta = true;
        return this;
    }
}
