import {SelfWritingJson} from "../selfWritingJson";

export class TemplatePool extends SelfWritingJson {
    static outputPath = "data/<internalNamespace>/worldgen/template_pool/<internalName>.json";
    fallback = "minecraft:empty";
    elements = [];
    autogenerated = false;

    constructor(name: string = "", namespace: string = "") {
        super(namespace, name, TemplatePool.outputPath);
    }

    withStructure(structure: string) {
        this.elements.push({
            element: {
                element_type: "minecraft:single_pool_element",
                projection: "rigid",
                processors: "minecraft:empty",
                location: structure
            },
            weight: 1
        })
        return this;
    }

}
