const fs = require('fs')
const sync_util = require('../sync_util')
const dataPackPath = '../../config/paxi/datapacks/generated_pmmo_mob_tags'
const configPath = '../configs/pmmo_entityType_kubeJs_dump'
const mcMetaTemplatePath = '../configs/template.mcmeta'
const config = fs.readFileSync(configPath, 'utf8');

// CREATE DATA
let result = config.split('\n');
result = result.map(line => line.replace('\r', ''));
result = result.filter((line) => line !== '');

// CREATE DP
let path = dataPackPath;
sync_util.ensureDirSync(path);
let mcMetaTemplate = fs.readFileSync(mcMetaTemplatePath, 'utf8');
let mcMeta = mcMetaTemplate.replace('{description}', 'Generated by pmmo_entityType_pmmoMobs_dp_gen.js');
fs.writeFileSync(path + '/pack.mcmeta', mcMeta);

path += '/data';
sync_util.ensureDirSync(path);
path += '/pmmo';
sync_util.ensureDirSync(path);
path += '/tags';
sync_util.ensureDirSync(path);
path += '/entity_types';
sync_util.ensureDirSync(path);
path += '/mobs.json';
const finalJson = {
    values: result
}
const finalJsonString = JSON.stringify(finalJson, null, 4);
fs.writeFileSync(path, finalJsonString);
console.log("Generated pmmo_entityType_pmmoMobs_dp_gen.js");

