
StartupEvents.registry("item", e => {
e.create("zoomers_armory:flint_dagger", "sword").displayName("Flint Dagger").texture("zoomers_armory:textures/item/zoomers_armory:flint_dagger").maxDamage(90);
e.create("zoomers_armory:flint_shortsword", "sword").displayName("Flint Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:flint_shortsword").maxDamage(100);
e.create("zoomers_armory:flint_heavysword", "sword").displayName("Flint Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:flint_heavysword").maxDamage(150);
e.create("zoomers_armory:flint_cutlass", "sword").displayName("Flint Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:flint_cutlass").maxDamage(120);
e.create("zoomers_armory:flint_mace", "sword").displayName("Flint Mace").texture("zoomers_armory:textures/item/zoomers_armory:flint_mace").maxDamage(120);
e.create("zoomers_armory:flint_heavymace", "sword").displayName("Flint Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:flint_heavymace").maxDamage(150);
e.create("zoomers_armory:flint_warhammer", "sword").displayName("Flint Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:flint_warhammer").maxDamage(180);
e.create("zoomers_armory:flint_spear", "sword").displayName("Flint Spear").texture("zoomers_armory:textures/item/zoomers_armory:flint_spear").maxDamage(100);
e.create("zoomers_armory:flint_halberd", "sword").displayName("Flint Halberd").texture("zoomers_armory:textures/item/zoomers_armory:flint_halberd").maxDamage(120);
e.create("zoomers_armory:flint_buckler", "shield").displayName("Flint Buckler").texture("zoomers_armory:textures/item/zoomers_armory:flint_buckler").maxDamage(90);
e.create("zoomers_armory:flint_heater", "shield").displayName("Flint Heater").texture("zoomers_armory:textures/item/zoomers_armory:flint_heater").maxDamage(120);
e.create("zoomers_armory:flint_tower", "shield").displayName("Flint Tower").texture("zoomers_armory:textures/item/zoomers_armory:flint_tower").maxDamage(150);
e.create("zoomers_armory:iron_dagger", "sword").displayName("Iron Dagger").texture("zoomers_armory:textures/item/zoomers_armory:iron_dagger").maxDamage(225);
e.create("zoomers_armory:iron_shortsword", "sword").displayName("Iron Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:iron_shortsword").maxDamage(250);
e.create("zoomers_armory:iron_heavysword", "sword").displayName("Iron Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:iron_heavysword").maxDamage(375);
e.create("zoomers_armory:iron_cutlass", "sword").displayName("Iron Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:iron_cutlass").maxDamage(300);
e.create("zoomers_armory:iron_mace", "sword").displayName("Iron Mace").texture("zoomers_armory:textures/item/zoomers_armory:iron_mace").maxDamage(300);
e.create("zoomers_armory:iron_heavymace", "sword").displayName("Iron Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:iron_heavymace").maxDamage(375);
e.create("zoomers_armory:iron_warhammer", "sword").displayName("Iron Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:iron_warhammer").maxDamage(450);
e.create("zoomers_armory:iron_spear", "sword").displayName("Iron Spear").texture("zoomers_armory:textures/item/zoomers_armory:iron_spear").maxDamage(250);
e.create("zoomers_armory:iron_halberd", "sword").displayName("Iron Halberd").texture("zoomers_armory:textures/item/zoomers_armory:iron_halberd").maxDamage(300);
e.create("zoomers_armory:iron_buckler", "shield").displayName("Iron Buckler").texture("zoomers_armory:textures/item/zoomers_armory:iron_buckler").maxDamage(225);
e.create("zoomers_armory:iron_heater", "shield").displayName("Iron Heater").texture("zoomers_armory:textures/item/zoomers_armory:iron_heater").maxDamage(300);
e.create("zoomers_armory:iron_tower", "shield").displayName("Iron Tower").texture("zoomers_armory:textures/item/zoomers_armory:iron_tower").maxDamage(375);
e.create("zoomers_armory:gold_dagger", "sword").displayName("Gold Dagger").texture("zoomers_armory:textures/item/zoomers_armory:gold_dagger").maxDamage(45);
e.create("zoomers_armory:gold_shortsword", "sword").displayName("Gold Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:gold_shortsword").maxDamage(50);
e.create("zoomers_armory:gold_heavysword", "sword").displayName("Gold Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:gold_heavysword").maxDamage(75);
e.create("zoomers_armory:gold_cutlass", "sword").displayName("Gold Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:gold_cutlass").maxDamage(60);
e.create("zoomers_armory:gold_mace", "sword").displayName("Gold Mace").texture("zoomers_armory:textures/item/zoomers_armory:gold_mace").maxDamage(60);
e.create("zoomers_armory:gold_heavymace", "sword").displayName("Gold Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:gold_heavymace").maxDamage(75);
e.create("zoomers_armory:gold_warhammer", "sword").displayName("Gold Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:gold_warhammer").maxDamage(90);
e.create("zoomers_armory:gold_spear", "sword").displayName("Gold Spear").texture("zoomers_armory:textures/item/zoomers_armory:gold_spear").maxDamage(50);
e.create("zoomers_armory:gold_halberd", "sword").displayName("Gold Halberd").texture("zoomers_armory:textures/item/zoomers_armory:gold_halberd").maxDamage(60);
e.create("zoomers_armory:gold_buckler", "shield").displayName("Gold Buckler").texture("zoomers_armory:textures/item/zoomers_armory:gold_buckler").maxDamage(45);
e.create("zoomers_armory:gold_heater", "shield").displayName("Gold Heater").texture("zoomers_armory:textures/item/zoomers_armory:gold_heater").maxDamage(60);
e.create("zoomers_armory:gold_tower", "shield").displayName("Gold Tower").texture("zoomers_armory:textures/item/zoomers_armory:gold_tower").maxDamage(75);
e.create("zoomers_armory:diamond_dagger", "sword").displayName("Diamond Dagger").texture("zoomers_armory:textures/item/zoomers_armory:diamond_dagger").maxDamage(450);
e.create("zoomers_armory:diamond_shortsword", "sword").displayName("Diamond Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:diamond_shortsword").maxDamage(500);
e.create("zoomers_armory:diamond_heavysword", "sword").displayName("Diamond Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:diamond_heavysword").maxDamage(750);
e.create("zoomers_armory:diamond_cutlass", "sword").displayName("Diamond Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:diamond_cutlass").maxDamage(600);
e.create("zoomers_armory:diamond_mace", "sword").displayName("Diamond Mace").texture("zoomers_armory:textures/item/zoomers_armory:diamond_mace").maxDamage(600);
e.create("zoomers_armory:diamond_heavymace", "sword").displayName("Diamond Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:diamond_heavymace").maxDamage(750);
e.create("zoomers_armory:diamond_warhammer", "sword").displayName("Diamond Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:diamond_warhammer").maxDamage(900);
e.create("zoomers_armory:diamond_spear", "sword").displayName("Diamond Spear").texture("zoomers_armory:textures/item/zoomers_armory:diamond_spear").maxDamage(500);
e.create("zoomers_armory:diamond_halberd", "sword").displayName("Diamond Halberd").texture("zoomers_armory:textures/item/zoomers_armory:diamond_halberd").maxDamage(600);
e.create("zoomers_armory:diamond_buckler", "shield").displayName("Diamond Buckler").texture("zoomers_armory:textures/item/zoomers_armory:diamond_buckler").maxDamage(450);
e.create("zoomers_armory:diamond_heater", "shield").displayName("Diamond Heater").texture("zoomers_armory:textures/item/zoomers_armory:diamond_heater").maxDamage(600);
e.create("zoomers_armory:diamond_tower", "shield").displayName("Diamond Tower").texture("zoomers_armory:textures/item/zoomers_armory:diamond_tower").maxDamage(750);
e.create("zoomers_armory:netherite_dagger", "sword").displayName("Netherite Dagger").texture("zoomers_armory:textures/item/zoomers_armory:netherite_dagger").maxDamage(1485);
e.create("zoomers_armory:netherite_shortsword", "sword").displayName("Netherite Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:netherite_shortsword").maxDamage(1650);
e.create("zoomers_armory:netherite_heavysword", "sword").displayName("Netherite Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:netherite_heavysword").maxDamage(2475);
e.create("zoomers_armory:netherite_cutlass", "sword").displayName("Netherite Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:netherite_cutlass").maxDamage(1980);
e.create("zoomers_armory:netherite_mace", "sword").displayName("Netherite Mace").texture("zoomers_armory:textures/item/zoomers_armory:netherite_mace").maxDamage(1980);
e.create("zoomers_armory:netherite_heavymace", "sword").displayName("Netherite Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:netherite_heavymace").maxDamage(2475);
e.create("zoomers_armory:netherite_warhammer", "sword").displayName("Netherite Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:netherite_warhammer").maxDamage(2970);
e.create("zoomers_armory:netherite_spear", "sword").displayName("Netherite Spear").texture("zoomers_armory:textures/item/zoomers_armory:netherite_spear").maxDamage(1650);
e.create("zoomers_armory:netherite_halberd", "sword").displayName("Netherite Halberd").texture("zoomers_armory:textures/item/zoomers_armory:netherite_halberd").maxDamage(1980);
e.create("zoomers_armory:netherite_buckler", "shield").displayName("Netherite Buckler").texture("zoomers_armory:textures/item/zoomers_armory:netherite_buckler").maxDamage(1485);
e.create("zoomers_armory:netherite_heater", "shield").displayName("Netherite Heater").texture("zoomers_armory:textures/item/zoomers_armory:netherite_heater").maxDamage(1980);
e.create("zoomers_armory:netherite_tower", "shield").displayName("Netherite Tower").texture("zoomers_armory:textures/item/zoomers_armory:netherite_tower").maxDamage(2475);
e.create("zoomers_armory:pyrope_dagger", "sword").displayName("Pyrope Dagger").texture("zoomers_armory:textures/item/zoomers_armory:pyrope_dagger").maxDamage(720);
e.create("zoomers_armory:pyrope_shortsword", "sword").displayName("Pyrope Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:pyrope_shortsword").maxDamage(800);
e.create("zoomers_armory:pyrope_heavysword", "sword").displayName("Pyrope Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:pyrope_heavysword").maxDamage(1200);
e.create("zoomers_armory:pyrope_cutlass", "sword").displayName("Pyrope Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:pyrope_cutlass").maxDamage(960);
e.create("zoomers_armory:pyrope_mace", "sword").displayName("Pyrope Mace").texture("zoomers_armory:textures/item/zoomers_armory:pyrope_mace").maxDamage(960);
e.create("zoomers_armory:pyrope_heavymace", "sword").displayName("Pyrope Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:pyrope_heavymace").maxDamage(1200);
e.create("zoomers_armory:pyrope_warhammer", "sword").displayName("Pyrope Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:pyrope_warhammer").maxDamage(1440);
e.create("zoomers_armory:pyrope_spear", "sword").displayName("Pyrope Spear").texture("zoomers_armory:textures/item/zoomers_armory:pyrope_spear").maxDamage(800);
e.create("zoomers_armory:pyrope_halberd", "sword").displayName("Pyrope Halberd").texture("zoomers_armory:textures/item/zoomers_armory:pyrope_halberd").maxDamage(960);
e.create("zoomers_armory:pyrope_buckler", "shield").displayName("Pyrope Buckler").texture("zoomers_armory:textures/item/zoomers_armory:pyrope_buckler").maxDamage(720);
e.create("zoomers_armory:pyrope_heater", "shield").displayName("Pyrope Heater").texture("zoomers_armory:textures/item/zoomers_armory:pyrope_heater").maxDamage(960);
e.create("zoomers_armory:pyrope_tower", "shield").displayName("Pyrope Tower").texture("zoomers_armory:textures/item/zoomers_armory:pyrope_tower").maxDamage(1200);
e.create("zoomers_armory:aquite_dagger", "sword").displayName("Aquite Dagger").texture("zoomers_armory:textures/item/zoomers_armory:aquite_dagger").maxDamage(765);
e.create("zoomers_armory:aquite_shortsword", "sword").displayName("Aquite Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:aquite_shortsword").maxDamage(850);
e.create("zoomers_armory:aquite_heavysword", "sword").displayName("Aquite Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:aquite_heavysword").maxDamage(1275);
e.create("zoomers_armory:aquite_cutlass", "sword").displayName("Aquite Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:aquite_cutlass").maxDamage(1020);
e.create("zoomers_armory:aquite_mace", "sword").displayName("Aquite Mace").texture("zoomers_armory:textures/item/zoomers_armory:aquite_mace").maxDamage(1020);
e.create("zoomers_armory:aquite_heavymace", "sword").displayName("Aquite Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:aquite_heavymace").maxDamage(1275);
e.create("zoomers_armory:aquite_warhammer", "sword").displayName("Aquite Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:aquite_warhammer").maxDamage(1530);
e.create("zoomers_armory:aquite_spear", "sword").displayName("Aquite Spear").texture("zoomers_armory:textures/item/zoomers_armory:aquite_spear").maxDamage(850);
e.create("zoomers_armory:aquite_halberd", "sword").displayName("Aquite Halberd").texture("zoomers_armory:textures/item/zoomers_armory:aquite_halberd").maxDamage(1020);
e.create("zoomers_armory:aquite_buckler", "shield").displayName("Aquite Buckler").texture("zoomers_armory:textures/item/zoomers_armory:aquite_buckler").maxDamage(765);
e.create("zoomers_armory:aquite_heater", "shield").displayName("Aquite Heater").texture("zoomers_armory:textures/item/zoomers_armory:aquite_heater").maxDamage(1020);
e.create("zoomers_armory:aquite_tower", "shield").displayName("Aquite Tower").texture("zoomers_armory:textures/item/zoomers_armory:aquite_tower").maxDamage(1275);
e.create("zoomers_armory:diopside_dagger", "sword").displayName("Diopside Dagger").texture("zoomers_armory:textures/item/zoomers_armory:diopside_dagger").maxDamage(810);
e.create("zoomers_armory:diopside_shortsword", "sword").displayName("Diopside Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:diopside_shortsword").maxDamage(900);
e.create("zoomers_armory:diopside_heavysword", "sword").displayName("Diopside Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:diopside_heavysword").maxDamage(1350);
e.create("zoomers_armory:diopside_cutlass", "sword").displayName("Diopside Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:diopside_cutlass").maxDamage(1080);
e.create("zoomers_armory:diopside_mace", "sword").displayName("Diopside Mace").texture("zoomers_armory:textures/item/zoomers_armory:diopside_mace").maxDamage(1080);
e.create("zoomers_armory:diopside_heavymace", "sword").displayName("Diopside Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:diopside_heavymace").maxDamage(1350);
e.create("zoomers_armory:diopside_warhammer", "sword").displayName("Diopside Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:diopside_warhammer").maxDamage(1620);
e.create("zoomers_armory:diopside_spear", "sword").displayName("Diopside Spear").texture("zoomers_armory:textures/item/zoomers_armory:diopside_spear").maxDamage(900);
e.create("zoomers_armory:diopside_halberd", "sword").displayName("Diopside Halberd").texture("zoomers_armory:textures/item/zoomers_armory:diopside_halberd").maxDamage(1080);
e.create("zoomers_armory:diopside_buckler", "shield").displayName("Diopside Buckler").texture("zoomers_armory:textures/item/zoomers_armory:diopside_buckler").maxDamage(810);
e.create("zoomers_armory:diopside_heater", "shield").displayName("Diopside Heater").texture("zoomers_armory:textures/item/zoomers_armory:diopside_heater").maxDamage(1080);
e.create("zoomers_armory:diopside_tower", "shield").displayName("Diopside Tower").texture("zoomers_armory:textures/item/zoomers_armory:diopside_tower").maxDamage(1350);
e.create("zoomers_armory:charoite_dagger", "sword").displayName("Charoite Dagger").texture("zoomers_armory:textures/item/zoomers_armory:charoite_dagger").maxDamage(855);
e.create("zoomers_armory:charoite_shortsword", "sword").displayName("Charoite Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:charoite_shortsword").maxDamage(950);
e.create("zoomers_armory:charoite_heavysword", "sword").displayName("Charoite Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:charoite_heavysword").maxDamage(1425);
e.create("zoomers_armory:charoite_cutlass", "sword").displayName("Charoite Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:charoite_cutlass").maxDamage(1140);
e.create("zoomers_armory:charoite_mace", "sword").displayName("Charoite Mace").texture("zoomers_armory:textures/item/zoomers_armory:charoite_mace").maxDamage(1140);
e.create("zoomers_armory:charoite_heavymace", "sword").displayName("Charoite Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:charoite_heavymace").maxDamage(1425);
e.create("zoomers_armory:charoite_warhammer", "sword").displayName("Charoite Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:charoite_warhammer").maxDamage(1710);
e.create("zoomers_armory:charoite_spear", "sword").displayName("Charoite Spear").texture("zoomers_armory:textures/item/zoomers_armory:charoite_spear").maxDamage(950);
e.create("zoomers_armory:charoite_halberd", "sword").displayName("Charoite Halberd").texture("zoomers_armory:textures/item/zoomers_armory:charoite_halberd").maxDamage(1140);
e.create("zoomers_armory:charoite_buckler", "shield").displayName("Charoite Buckler").texture("zoomers_armory:textures/item/zoomers_armory:charoite_buckler").maxDamage(855);
e.create("zoomers_armory:charoite_heater", "shield").displayName("Charoite Heater").texture("zoomers_armory:textures/item/zoomers_armory:charoite_heater").maxDamage(1140);
e.create("zoomers_armory:charoite_tower", "shield").displayName("Charoite Tower").texture("zoomers_armory:textures/item/zoomers_armory:charoite_tower").maxDamage(1425);
e.create("zoomers_armory:horizonite_dagger", "sword").displayName("Horizonite Dagger").texture("zoomers_armory:textures/item/zoomers_armory:horizonite_dagger").maxDamage(900);
e.create("zoomers_armory:horizonite_shortsword", "sword").displayName("Horizonite Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:horizonite_shortsword").maxDamage(1000);
e.create("zoomers_armory:horizonite_heavysword", "sword").displayName("Horizonite Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:horizonite_heavysword").maxDamage(1500);
e.create("zoomers_armory:horizonite_cutlass", "sword").displayName("Horizonite Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:horizonite_cutlass").maxDamage(1200);
e.create("zoomers_armory:horizonite_mace", "sword").displayName("Horizonite Mace").texture("zoomers_armory:textures/item/zoomers_armory:horizonite_mace").maxDamage(1200);
e.create("zoomers_armory:horizonite_heavymace", "sword").displayName("Horizonite Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:horizonite_heavymace").maxDamage(1500);
e.create("zoomers_armory:horizonite_warhammer", "sword").displayName("Horizonite Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:horizonite_warhammer").maxDamage(1800);
e.create("zoomers_armory:horizonite_spear", "sword").displayName("Horizonite Spear").texture("zoomers_armory:textures/item/zoomers_armory:horizonite_spear").maxDamage(1000);
e.create("zoomers_armory:horizonite_halberd", "sword").displayName("Horizonite Halberd").texture("zoomers_armory:textures/item/zoomers_armory:horizonite_halberd").maxDamage(1200);
e.create("zoomers_armory:horizonite_buckler", "shield").displayName("Horizonite Buckler").texture("zoomers_armory:textures/item/zoomers_armory:horizonite_buckler").maxDamage(900);
e.create("zoomers_armory:horizonite_heater", "shield").displayName("Horizonite Heater").texture("zoomers_armory:textures/item/zoomers_armory:horizonite_heater").maxDamage(1200);
e.create("zoomers_armory:horizonite_tower", "shield").displayName("Horizonite Tower").texture("zoomers_armory:textures/item/zoomers_armory:horizonite_tower").maxDamage(1500);
e.create("zoomers_armory:zanite_dagger", "sword").displayName("Zanite Dagger").texture("zoomers_armory:textures/item/zoomers_armory:zanite_dagger").maxDamage(990);
e.create("zoomers_armory:zanite_shortsword", "sword").displayName("Zanite Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:zanite_shortsword").maxDamage(1100);
e.create("zoomers_armory:zanite_heavysword", "sword").displayName("Zanite Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:zanite_heavysword").maxDamage(1650);
e.create("zoomers_armory:zanite_cutlass", "sword").displayName("Zanite Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:zanite_cutlass").maxDamage(1320);
e.create("zoomers_armory:zanite_mace", "sword").displayName("Zanite Mace").texture("zoomers_armory:textures/item/zoomers_armory:zanite_mace").maxDamage(1320);
e.create("zoomers_armory:zanite_heavymace", "sword").displayName("Zanite Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:zanite_heavymace").maxDamage(1650);
e.create("zoomers_armory:zanite_warhammer", "sword").displayName("Zanite Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:zanite_warhammer").maxDamage(1980);
e.create("zoomers_armory:zanite_spear", "sword").displayName("Zanite Spear").texture("zoomers_armory:textures/item/zoomers_armory:zanite_spear").maxDamage(1100);
e.create("zoomers_armory:zanite_halberd", "sword").displayName("Zanite Halberd").texture("zoomers_armory:textures/item/zoomers_armory:zanite_halberd").maxDamage(1320);
e.create("zoomers_armory:zanite_buckler", "shield").displayName("Zanite Buckler").texture("zoomers_armory:textures/item/zoomers_armory:zanite_buckler").maxDamage(990);
e.create("zoomers_armory:zanite_heater", "shield").displayName("Zanite Heater").texture("zoomers_armory:textures/item/zoomers_armory:zanite_heater").maxDamage(1320);
e.create("zoomers_armory:zanite_tower", "shield").displayName("Zanite Tower").texture("zoomers_armory:textures/item/zoomers_armory:zanite_tower").maxDamage(1650);
e.create("zoomers_armory:enchanted_gravitite_dagger", "sword").displayName("Enchanted gravitite Dagger").texture("zoomers_armory:textures/item/zoomers_armory:enchanted_gravitite_dagger").maxDamage(1080);
e.create("zoomers_armory:enchanted_gravitite_shortsword", "sword").displayName("Enchanted gravitite Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:enchanted_gravitite_shortsword").maxDamage(1200);
e.create("zoomers_armory:enchanted_gravitite_heavysword", "sword").displayName("Enchanted gravitite Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:enchanted_gravitite_heavysword").maxDamage(1800);
e.create("zoomers_armory:enchanted_gravitite_cutlass", "sword").displayName("Enchanted gravitite Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:enchanted_gravitite_cutlass").maxDamage(1440);
e.create("zoomers_armory:enchanted_gravitite_mace", "sword").displayName("Enchanted gravitite Mace").texture("zoomers_armory:textures/item/zoomers_armory:enchanted_gravitite_mace").maxDamage(1440);
e.create("zoomers_armory:enchanted_gravitite_heavymace", "sword").displayName("Enchanted gravitite Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:enchanted_gravitite_heavymace").maxDamage(1800);
e.create("zoomers_armory:enchanted_gravitite_warhammer", "sword").displayName("Enchanted gravitite Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:enchanted_gravitite_warhammer").maxDamage(2160);
e.create("zoomers_armory:enchanted_gravitite_spear", "sword").displayName("Enchanted gravitite Spear").texture("zoomers_armory:textures/item/zoomers_armory:enchanted_gravitite_spear").maxDamage(1200);
e.create("zoomers_armory:enchanted_gravitite_halberd", "sword").displayName("Enchanted gravitite Halberd").texture("zoomers_armory:textures/item/zoomers_armory:enchanted_gravitite_halberd").maxDamage(1440);
e.create("zoomers_armory:enchanted_gravitite_buckler", "shield").displayName("Enchanted_gravitite Buckler").texture("zoomers_armory:textures/item/zoomers_armory:enchanted_gravitite_buckler").maxDamage(1080);
e.create("zoomers_armory:enchanted_gravitite_heater", "shield").displayName("Enchanted_gravitite Heater").texture("zoomers_armory:textures/item/zoomers_armory:enchanted_gravitite_heater").maxDamage(1440);
e.create("zoomers_armory:enchanted_gravitite_tower", "shield").displayName("Enchanted_gravitite Tower").texture("zoomers_armory:textures/item/zoomers_armory:enchanted_gravitite_tower").maxDamage(1800);
e.create("zoomers_armory:cincinnasite_dagger", "sword").displayName("Cincinnasite Dagger").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_dagger").maxDamage(1170);
e.create("zoomers_armory:cincinnasite_shortsword", "sword").displayName("Cincinnasite Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_shortsword").maxDamage(1300);
e.create("zoomers_armory:cincinnasite_heavysword", "sword").displayName("Cincinnasite Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_heavysword").maxDamage(1950);
e.create("zoomers_armory:cincinnasite_cutlass", "sword").displayName("Cincinnasite Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_cutlass").maxDamage(1560);
e.create("zoomers_armory:cincinnasite_mace", "sword").displayName("Cincinnasite Mace").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_mace").maxDamage(1560);
e.create("zoomers_armory:cincinnasite_heavymace", "sword").displayName("Cincinnasite Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_heavymace").maxDamage(1950);
e.create("zoomers_armory:cincinnasite_warhammer", "sword").displayName("Cincinnasite Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_warhammer").maxDamage(2340);
e.create("zoomers_armory:cincinnasite_spear", "sword").displayName("Cincinnasite Spear").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_spear").maxDamage(1300);
e.create("zoomers_armory:cincinnasite_halberd", "sword").displayName("Cincinnasite Halberd").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_halberd").maxDamage(1560);
e.create("zoomers_armory:cincinnasite_buckler", "shield").displayName("Cincinnasite Buckler").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_buckler").maxDamage(1170);
e.create("zoomers_armory:cincinnasite_heater", "shield").displayName("Cincinnasite Heater").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_heater").maxDamage(1560);
e.create("zoomers_armory:cincinnasite_tower", "shield").displayName("Cincinnasite Tower").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_tower").maxDamage(1950);
e.create("zoomers_armory:cincinnasite_diamond_dagger", "sword").displayName("Cincinnasite diamond Dagger").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_diamond_dagger").maxDamage(1260);
e.create("zoomers_armory:cincinnasite_diamond_shortsword", "sword").displayName("Cincinnasite diamond Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_diamond_shortsword").maxDamage(1400);
e.create("zoomers_armory:cincinnasite_diamond_heavysword", "sword").displayName("Cincinnasite diamond Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_diamond_heavysword").maxDamage(2100);
e.create("zoomers_armory:cincinnasite_diamond_cutlass", "sword").displayName("Cincinnasite diamond Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_diamond_cutlass").maxDamage(1680);
e.create("zoomers_armory:cincinnasite_diamond_mace", "sword").displayName("Cincinnasite diamond Mace").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_diamond_mace").maxDamage(1680);
e.create("zoomers_armory:cincinnasite_diamond_heavymace", "sword").displayName("Cincinnasite diamond Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_diamond_heavymace").maxDamage(2100);
e.create("zoomers_armory:cincinnasite_diamond_warhammer", "sword").displayName("Cincinnasite diamond Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_diamond_warhammer").maxDamage(2520);
e.create("zoomers_armory:cincinnasite_diamond_spear", "sword").displayName("Cincinnasite diamond Spear").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_diamond_spear").maxDamage(1400);
e.create("zoomers_armory:cincinnasite_diamond_halberd", "sword").displayName("Cincinnasite diamond Halberd").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_diamond_halberd").maxDamage(1680);
e.create("zoomers_armory:cincinnasite_diamond_buckler", "shield").displayName("Cincinnasite_diamond Buckler").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_diamond_buckler").maxDamage(1260);
e.create("zoomers_armory:cincinnasite_diamond_heater", "shield").displayName("Cincinnasite_diamond Heater").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_diamond_heater").maxDamage(1680);
e.create("zoomers_armory:cincinnasite_diamond_tower", "shield").displayName("Cincinnasite_diamond Tower").texture("zoomers_armory:textures/item/zoomers_armory:cincinnasite_diamond_tower").maxDamage(2100);
e.create("zoomers_armory:nether_ruby_dagger", "sword").displayName("Nether ruby Dagger").texture("zoomers_armory:textures/item/zoomers_armory:nether_ruby_dagger").maxDamage(1350);
e.create("zoomers_armory:nether_ruby_shortsword", "sword").displayName("Nether ruby Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:nether_ruby_shortsword").maxDamage(1500);
e.create("zoomers_armory:nether_ruby_heavysword", "sword").displayName("Nether ruby Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:nether_ruby_heavysword").maxDamage(2250);
e.create("zoomers_armory:nether_ruby_cutlass", "sword").displayName("Nether ruby Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:nether_ruby_cutlass").maxDamage(1800);
e.create("zoomers_armory:nether_ruby_mace", "sword").displayName("Nether ruby Mace").texture("zoomers_armory:textures/item/zoomers_armory:nether_ruby_mace").maxDamage(1800);
e.create("zoomers_armory:nether_ruby_heavymace", "sword").displayName("Nether ruby Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:nether_ruby_heavymace").maxDamage(2250);
e.create("zoomers_armory:nether_ruby_warhammer", "sword").displayName("Nether ruby Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:nether_ruby_warhammer").maxDamage(2700);
e.create("zoomers_armory:nether_ruby_spear", "sword").displayName("Nether ruby Spear").texture("zoomers_armory:textures/item/zoomers_armory:nether_ruby_spear").maxDamage(1500);
e.create("zoomers_armory:nether_ruby_halberd", "sword").displayName("Nether ruby Halberd").texture("zoomers_armory:textures/item/zoomers_armory:nether_ruby_halberd").maxDamage(1800);
e.create("zoomers_armory:nether_ruby_buckler", "shield").displayName("Nether_ruby Buckler").texture("zoomers_armory:textures/item/zoomers_armory:nether_ruby_buckler").maxDamage(1350);
e.create("zoomers_armory:nether_ruby_heater", "shield").displayName("Nether_ruby Heater").texture("zoomers_armory:textures/item/zoomers_armory:nether_ruby_heater").maxDamage(1800);
e.create("zoomers_armory:nether_ruby_tower", "shield").displayName("Nether_ruby Tower").texture("zoomers_armory:textures/item/zoomers_armory:nether_ruby_tower").maxDamage(2250);
e.create("zoomers_armory:flaming_ruby_dagger", "sword").displayName("Flaming ruby Dagger").texture("zoomers_armory:textures/item/zoomers_armory:flaming_ruby_dagger").maxDamage(1440);
e.create("zoomers_armory:flaming_ruby_shortsword", "sword").displayName("Flaming ruby Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:flaming_ruby_shortsword").maxDamage(1600);
e.create("zoomers_armory:flaming_ruby_heavysword", "sword").displayName("Flaming ruby Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:flaming_ruby_heavysword").maxDamage(2400);
e.create("zoomers_armory:flaming_ruby_cutlass", "sword").displayName("Flaming ruby Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:flaming_ruby_cutlass").maxDamage(1920);
e.create("zoomers_armory:flaming_ruby_mace", "sword").displayName("Flaming ruby Mace").texture("zoomers_armory:textures/item/zoomers_armory:flaming_ruby_mace").maxDamage(1920);
e.create("zoomers_armory:flaming_ruby_heavymace", "sword").displayName("Flaming ruby Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:flaming_ruby_heavymace").maxDamage(2400);
e.create("zoomers_armory:flaming_ruby_warhammer", "sword").displayName("Flaming ruby Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:flaming_ruby_warhammer").maxDamage(2880);
e.create("zoomers_armory:flaming_ruby_spear", "sword").displayName("Flaming ruby Spear").texture("zoomers_armory:textures/item/zoomers_armory:flaming_ruby_spear").maxDamage(1600);
e.create("zoomers_armory:flaming_ruby_halberd", "sword").displayName("Flaming ruby Halberd").texture("zoomers_armory:textures/item/zoomers_armory:flaming_ruby_halberd").maxDamage(1920);
e.create("zoomers_armory:flaming_ruby_buckler", "shield").displayName("Flaming_ruby Buckler").texture("zoomers_armory:textures/item/zoomers_armory:flaming_ruby_buckler").maxDamage(1440);
e.create("zoomers_armory:flaming_ruby_heater", "shield").displayName("Flaming_ruby Heater").texture("zoomers_armory:textures/item/zoomers_armory:flaming_ruby_heater").maxDamage(1920);
e.create("zoomers_armory:flaming_ruby_tower", "shield").displayName("Flaming_ruby Tower").texture("zoomers_armory:textures/item/zoomers_armory:flaming_ruby_tower").maxDamage(2400);
e.create("zoomers_armory:cloggrum_dagger", "sword").displayName("Cloggrum Dagger").texture("zoomers_armory:textures/item/zoomers_armory:cloggrum_dagger").maxDamage(1530);
e.create("zoomers_armory:cloggrum_shortsword", "sword").displayName("Cloggrum Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:cloggrum_shortsword").maxDamage(1700);
e.create("zoomers_armory:cloggrum_heavysword", "sword").displayName("Cloggrum Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:cloggrum_heavysword").maxDamage(2550);
e.create("zoomers_armory:cloggrum_cutlass", "sword").displayName("Cloggrum Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:cloggrum_cutlass").maxDamage(2040);
e.create("zoomers_armory:cloggrum_mace", "sword").displayName("Cloggrum Mace").texture("zoomers_armory:textures/item/zoomers_armory:cloggrum_mace").maxDamage(2040);
e.create("zoomers_armory:cloggrum_heavymace", "sword").displayName("Cloggrum Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:cloggrum_heavymace").maxDamage(2550);
e.create("zoomers_armory:cloggrum_warhammer", "sword").displayName("Cloggrum Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:cloggrum_warhammer").maxDamage(3060);
e.create("zoomers_armory:cloggrum_spear", "sword").displayName("Cloggrum Spear").texture("zoomers_armory:textures/item/zoomers_armory:cloggrum_spear").maxDamage(1700);
e.create("zoomers_armory:cloggrum_halberd", "sword").displayName("Cloggrum Halberd").texture("zoomers_armory:textures/item/zoomers_armory:cloggrum_halberd").maxDamage(2040);
e.create("zoomers_armory:cloggrum_buckler", "shield").displayName("Cloggrum Buckler").texture("zoomers_armory:textures/item/zoomers_armory:cloggrum_buckler").maxDamage(1530);
e.create("zoomers_armory:cloggrum_heater", "shield").displayName("Cloggrum Heater").texture("zoomers_armory:textures/item/zoomers_armory:cloggrum_heater").maxDamage(2040);
e.create("zoomers_armory:cloggrum_tower", "shield").displayName("Cloggrum Tower").texture("zoomers_armory:textures/item/zoomers_armory:cloggrum_tower").maxDamage(2550);
e.create("zoomers_armory:froststeel_dagger", "sword").displayName("Froststeel Dagger").texture("zoomers_armory:textures/item/zoomers_armory:froststeel_dagger").maxDamage(1620);
e.create("zoomers_armory:froststeel_shortsword", "sword").displayName("Froststeel Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:froststeel_shortsword").maxDamage(1800);
e.create("zoomers_armory:froststeel_heavysword", "sword").displayName("Froststeel Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:froststeel_heavysword").maxDamage(2700);
e.create("zoomers_armory:froststeel_cutlass", "sword").displayName("Froststeel Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:froststeel_cutlass").maxDamage(2160);
e.create("zoomers_armory:froststeel_mace", "sword").displayName("Froststeel Mace").texture("zoomers_armory:textures/item/zoomers_armory:froststeel_mace").maxDamage(2160);
e.create("zoomers_armory:froststeel_heavymace", "sword").displayName("Froststeel Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:froststeel_heavymace").maxDamage(2700);
e.create("zoomers_armory:froststeel_warhammer", "sword").displayName("Froststeel Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:froststeel_warhammer").maxDamage(3240);
e.create("zoomers_armory:froststeel_spear", "sword").displayName("Froststeel Spear").texture("zoomers_armory:textures/item/zoomers_armory:froststeel_spear").maxDamage(1800);
e.create("zoomers_armory:froststeel_halberd", "sword").displayName("Froststeel Halberd").texture("zoomers_armory:textures/item/zoomers_armory:froststeel_halberd").maxDamage(2160);
e.create("zoomers_armory:froststeel_buckler", "shield").displayName("Froststeel Buckler").texture("zoomers_armory:textures/item/zoomers_armory:froststeel_buckler").maxDamage(1620);
e.create("zoomers_armory:froststeel_heater", "shield").displayName("Froststeel Heater").texture("zoomers_armory:textures/item/zoomers_armory:froststeel_heater").maxDamage(2160);
e.create("zoomers_armory:froststeel_tower", "shield").displayName("Froststeel Tower").texture("zoomers_armory:textures/item/zoomers_armory:froststeel_tower").maxDamage(2700);
e.create("zoomers_armory:utherium_dagger", "sword").displayName("Utherium Dagger").texture("zoomers_armory:textures/item/zoomers_armory:utherium_dagger").maxDamage(1710);
e.create("zoomers_armory:utherium_shortsword", "sword").displayName("Utherium Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:utherium_shortsword").maxDamage(1900);
e.create("zoomers_armory:utherium_heavysword", "sword").displayName("Utherium Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:utherium_heavysword").maxDamage(2850);
e.create("zoomers_armory:utherium_cutlass", "sword").displayName("Utherium Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:utherium_cutlass").maxDamage(2280);
e.create("zoomers_armory:utherium_mace", "sword").displayName("Utherium Mace").texture("zoomers_armory:textures/item/zoomers_armory:utherium_mace").maxDamage(2280);
e.create("zoomers_armory:utherium_heavymace", "sword").displayName("Utherium Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:utherium_heavymace").maxDamage(2850);
e.create("zoomers_armory:utherium_warhammer", "sword").displayName("Utherium Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:utherium_warhammer").maxDamage(3420);
e.create("zoomers_armory:utherium_spear", "sword").displayName("Utherium Spear").texture("zoomers_armory:textures/item/zoomers_armory:utherium_spear").maxDamage(1900);
e.create("zoomers_armory:utherium_halberd", "sword").displayName("Utherium Halberd").texture("zoomers_armory:textures/item/zoomers_armory:utherium_halberd").maxDamage(2280);
e.create("zoomers_armory:utherium_buckler", "shield").displayName("Utherium Buckler").texture("zoomers_armory:textures/item/zoomers_armory:utherium_buckler").maxDamage(1710);
e.create("zoomers_armory:utherium_heater", "shield").displayName("Utherium Heater").texture("zoomers_armory:textures/item/zoomers_armory:utherium_heater").maxDamage(2280);
e.create("zoomers_armory:utherium_tower", "shield").displayName("Utherium Tower").texture("zoomers_armory:textures/item/zoomers_armory:utherium_tower").maxDamage(2850);
e.create("zoomers_armory:forgotten_dagger", "sword").displayName("Forgotten Dagger").texture("zoomers_armory:textures/item/zoomers_armory:forgotten_dagger").maxDamage(1800);
e.create("zoomers_armory:forgotten_shortsword", "sword").displayName("Forgotten Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:forgotten_shortsword").maxDamage(2000);
e.create("zoomers_armory:forgotten_heavysword", "sword").displayName("Forgotten Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:forgotten_heavysword").maxDamage(3000);
e.create("zoomers_armory:forgotten_cutlass", "sword").displayName("Forgotten Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:forgotten_cutlass").maxDamage(2400);
e.create("zoomers_armory:forgotten_mace", "sword").displayName("Forgotten Mace").texture("zoomers_armory:textures/item/zoomers_armory:forgotten_mace").maxDamage(2400);
e.create("zoomers_armory:forgotten_heavymace", "sword").displayName("Forgotten Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:forgotten_heavymace").maxDamage(3000);
e.create("zoomers_armory:forgotten_warhammer", "sword").displayName("Forgotten Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:forgotten_warhammer").maxDamage(3600);
e.create("zoomers_armory:forgotten_spear", "sword").displayName("Forgotten Spear").texture("zoomers_armory:textures/item/zoomers_armory:forgotten_spear").maxDamage(2000);
e.create("zoomers_armory:forgotten_halberd", "sword").displayName("Forgotten Halberd").texture("zoomers_armory:textures/item/zoomers_armory:forgotten_halberd").maxDamage(2400);
e.create("zoomers_armory:forgotten_buckler", "shield").displayName("Forgotten Buckler").texture("zoomers_armory:textures/item/zoomers_armory:forgotten_buckler").maxDamage(1800);
e.create("zoomers_armory:forgotten_heater", "shield").displayName("Forgotten Heater").texture("zoomers_armory:textures/item/zoomers_armory:forgotten_heater").maxDamage(2400);
e.create("zoomers_armory:forgotten_tower", "shield").displayName("Forgotten Tower").texture("zoomers_armory:textures/item/zoomers_armory:forgotten_tower").maxDamage(3000);
e.create("zoomers_armory:thallasium_dagger", "sword").displayName("Thallasium Dagger").texture("zoomers_armory:textures/item/zoomers_armory:thallasium_dagger").maxDamage(1980);
e.create("zoomers_armory:thallasium_shortsword", "sword").displayName("Thallasium Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:thallasium_shortsword").maxDamage(2200);
e.create("zoomers_armory:thallasium_heavysword", "sword").displayName("Thallasium Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:thallasium_heavysword").maxDamage(3300);
e.create("zoomers_armory:thallasium_cutlass", "sword").displayName("Thallasium Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:thallasium_cutlass").maxDamage(2640);
e.create("zoomers_armory:thallasium_mace", "sword").displayName("Thallasium Mace").texture("zoomers_armory:textures/item/zoomers_armory:thallasium_mace").maxDamage(2640);
e.create("zoomers_armory:thallasium_heavymace", "sword").displayName("Thallasium Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:thallasium_heavymace").maxDamage(3300);
e.create("zoomers_armory:thallasium_warhammer", "sword").displayName("Thallasium Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:thallasium_warhammer").maxDamage(3960);
e.create("zoomers_armory:thallasium_spear", "sword").displayName("Thallasium Spear").texture("zoomers_armory:textures/item/zoomers_armory:thallasium_spear").maxDamage(2200);
e.create("zoomers_armory:thallasium_halberd", "sword").displayName("Thallasium Halberd").texture("zoomers_armory:textures/item/zoomers_armory:thallasium_halberd").maxDamage(2640);
e.create("zoomers_armory:thallasium_buckler", "shield").displayName("Thallasium Buckler").texture("zoomers_armory:textures/item/zoomers_armory:thallasium_buckler").maxDamage(1980);
e.create("zoomers_armory:thallasium_heater", "shield").displayName("Thallasium Heater").texture("zoomers_armory:textures/item/zoomers_armory:thallasium_heater").maxDamage(2640);
e.create("zoomers_armory:thallasium_tower", "shield").displayName("Thallasium Tower").texture("zoomers_armory:textures/item/zoomers_armory:thallasium_tower").maxDamage(3300);
e.create("zoomers_armory:terminite_dagger", "sword").displayName("Terminite Dagger").texture("zoomers_armory:textures/item/zoomers_armory:terminite_dagger").maxDamage(2160);
e.create("zoomers_armory:terminite_shortsword", "sword").displayName("Terminite Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:terminite_shortsword").maxDamage(2400);
e.create("zoomers_armory:terminite_heavysword", "sword").displayName("Terminite Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:terminite_heavysword").maxDamage(3600);
e.create("zoomers_armory:terminite_cutlass", "sword").displayName("Terminite Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:terminite_cutlass").maxDamage(2880);
e.create("zoomers_armory:terminite_mace", "sword").displayName("Terminite Mace").texture("zoomers_armory:textures/item/zoomers_armory:terminite_mace").maxDamage(2880);
e.create("zoomers_armory:terminite_heavymace", "sword").displayName("Terminite Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:terminite_heavymace").maxDamage(3600);
e.create("zoomers_armory:terminite_warhammer", "sword").displayName("Terminite Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:terminite_warhammer").maxDamage(4320);
e.create("zoomers_armory:terminite_spear", "sword").displayName("Terminite Spear").texture("zoomers_armory:textures/item/zoomers_armory:terminite_spear").maxDamage(2400);
e.create("zoomers_armory:terminite_halberd", "sword").displayName("Terminite Halberd").texture("zoomers_armory:textures/item/zoomers_armory:terminite_halberd").maxDamage(2880);
e.create("zoomers_armory:terminite_buckler", "shield").displayName("Terminite Buckler").texture("zoomers_armory:textures/item/zoomers_armory:terminite_buckler").maxDamage(2160);
e.create("zoomers_armory:terminite_heater", "shield").displayName("Terminite Heater").texture("zoomers_armory:textures/item/zoomers_armory:terminite_heater").maxDamage(2880);
e.create("zoomers_armory:terminite_tower", "shield").displayName("Terminite Tower").texture("zoomers_armory:textures/item/zoomers_armory:terminite_tower").maxDamage(3600);
e.create("zoomers_armory:aeternium_dagger", "sword").displayName("Aeternium Dagger").texture("zoomers_armory:textures/item/zoomers_armory:aeternium_dagger").maxDamage(2340);
e.create("zoomers_armory:aeternium_shortsword", "sword").displayName("Aeternium Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:aeternium_shortsword").maxDamage(2600);
e.create("zoomers_armory:aeternium_heavysword", "sword").displayName("Aeternium Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:aeternium_heavysword").maxDamage(3900);
e.create("zoomers_armory:aeternium_cutlass", "sword").displayName("Aeternium Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:aeternium_cutlass").maxDamage(3120);
e.create("zoomers_armory:aeternium_mace", "sword").displayName("Aeternium Mace").texture("zoomers_armory:textures/item/zoomers_armory:aeternium_mace").maxDamage(3120);
e.create("zoomers_armory:aeternium_heavymace", "sword").displayName("Aeternium Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:aeternium_heavymace").maxDamage(3900);
e.create("zoomers_armory:aeternium_warhammer", "sword").displayName("Aeternium Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:aeternium_warhammer").maxDamage(4680);
e.create("zoomers_armory:aeternium_spear", "sword").displayName("Aeternium Spear").texture("zoomers_armory:textures/item/zoomers_armory:aeternium_spear").maxDamage(2600);
e.create("zoomers_armory:aeternium_halberd", "sword").displayName("Aeternium Halberd").texture("zoomers_armory:textures/item/zoomers_armory:aeternium_halberd").maxDamage(3120);
e.create("zoomers_armory:aeternium_buckler", "shield").displayName("Aeternium Buckler").texture("zoomers_armory:textures/item/zoomers_armory:aeternium_buckler").maxDamage(2340);
e.create("zoomers_armory:aeternium_heater", "shield").displayName("Aeternium Heater").texture("zoomers_armory:textures/item/zoomers_armory:aeternium_heater").maxDamage(3120);
e.create("zoomers_armory:aeternium_tower", "shield").displayName("Aeternium Tower").texture("zoomers_armory:textures/item/zoomers_armory:aeternium_tower").maxDamage(3900);
e.create("zoomers_armory:aurora_dagger", "sword").displayName("Aurora Dagger").texture("zoomers_armory:textures/item/zoomers_armory:aurora_dagger").maxDamage(2520);
e.create("zoomers_armory:aurora_shortsword", "sword").displayName("Aurora Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:aurora_shortsword").maxDamage(2800);
e.create("zoomers_armory:aurora_heavysword", "sword").displayName("Aurora Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:aurora_heavysword").maxDamage(4200);
e.create("zoomers_armory:aurora_cutlass", "sword").displayName("Aurora Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:aurora_cutlass").maxDamage(3360);
e.create("zoomers_armory:aurora_mace", "sword").displayName("Aurora Mace").texture("zoomers_armory:textures/item/zoomers_armory:aurora_mace").maxDamage(3360);
e.create("zoomers_armory:aurora_heavymace", "sword").displayName("Aurora Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:aurora_heavymace").maxDamage(4200);
e.create("zoomers_armory:aurora_warhammer", "sword").displayName("Aurora Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:aurora_warhammer").maxDamage(5040);
e.create("zoomers_armory:aurora_spear", "sword").displayName("Aurora Spear").texture("zoomers_armory:textures/item/zoomers_armory:aurora_spear").maxDamage(2800);
e.create("zoomers_armory:aurora_halberd", "sword").displayName("Aurora Halberd").texture("zoomers_armory:textures/item/zoomers_armory:aurora_halberd").maxDamage(3360);
e.create("zoomers_armory:aurora_buckler", "shield").displayName("Aurora Buckler").texture("zoomers_armory:textures/item/zoomers_armory:aurora_buckler").maxDamage(2520);
e.create("zoomers_armory:aurora_heater", "shield").displayName("Aurora Heater").texture("zoomers_armory:textures/item/zoomers_armory:aurora_heater").maxDamage(3360);
e.create("zoomers_armory:aurora_tower", "shield").displayName("Aurora Tower").texture("zoomers_armory:textures/item/zoomers_armory:aurora_tower").maxDamage(4200);
e.create("zoomers_armory:immemorial_dagger", "sword").displayName("Immemorial Dagger").texture("zoomers_armory:textures/item/zoomers_armory:immemorial_dagger").maxDamage(2520);
e.create("zoomers_armory:immemorial_shortsword", "sword").displayName("Immemorial Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:immemorial_shortsword").maxDamage(2800);
e.create("zoomers_armory:immemorial_heavysword", "sword").displayName("Immemorial Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:immemorial_heavysword").maxDamage(4200);
e.create("zoomers_armory:immemorial_cutlass", "sword").displayName("Immemorial Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:immemorial_cutlass").maxDamage(3360);
e.create("zoomers_armory:immemorial_mace", "sword").displayName("Immemorial Mace").texture("zoomers_armory:textures/item/zoomers_armory:immemorial_mace").maxDamage(3360);
e.create("zoomers_armory:immemorial_heavymace", "sword").displayName("Immemorial Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:immemorial_heavymace").maxDamage(4200);
e.create("zoomers_armory:immemorial_warhammer", "sword").displayName("Immemorial Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:immemorial_warhammer").maxDamage(5040);
e.create("zoomers_armory:immemorial_spear", "sword").displayName("Immemorial Spear").texture("zoomers_armory:textures/item/zoomers_armory:immemorial_spear").maxDamage(2800);
e.create("zoomers_armory:immemorial_halberd", "sword").displayName("Immemorial Halberd").texture("zoomers_armory:textures/item/zoomers_armory:immemorial_halberd").maxDamage(3360);
e.create("zoomers_armory:immemorial_buckler", "shield").displayName("Immemorial Buckler").texture("zoomers_armory:textures/item/zoomers_armory:immemorial_buckler").maxDamage(2520);
e.create("zoomers_armory:immemorial_heater", "shield").displayName("Immemorial Heater").texture("zoomers_armory:textures/item/zoomers_armory:immemorial_heater").maxDamage(3360);
e.create("zoomers_armory:immemorial_tower", "shield").displayName("Immemorial Tower").texture("zoomers_armory:textures/item/zoomers_armory:immemorial_tower").maxDamage(4200);
e.create("zoomers_armory:fixed_bone_dagger", "sword").displayName("Fixed bone Dagger").texture("zoomers_armory:textures/item/zoomers_armory:fixed_bone_dagger").maxDamage(2880);
e.create("zoomers_armory:fixed_bone_shortsword", "sword").displayName("Fixed bone Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:fixed_bone_shortsword").maxDamage(3200);
e.create("zoomers_armory:fixed_bone_heavysword", "sword").displayName("Fixed bone Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:fixed_bone_heavysword").maxDamage(4800);
e.create("zoomers_armory:fixed_bone_cutlass", "sword").displayName("Fixed bone Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:fixed_bone_cutlass").maxDamage(3840);
e.create("zoomers_armory:fixed_bone_mace", "sword").displayName("Fixed bone Mace").texture("zoomers_armory:textures/item/zoomers_armory:fixed_bone_mace").maxDamage(3840);
e.create("zoomers_armory:fixed_bone_heavymace", "sword").displayName("Fixed bone Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:fixed_bone_heavymace").maxDamage(4800);
e.create("zoomers_armory:fixed_bone_warhammer", "sword").displayName("Fixed bone Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:fixed_bone_warhammer").maxDamage(5760);
e.create("zoomers_armory:fixed_bone_spear", "sword").displayName("Fixed bone Spear").texture("zoomers_armory:textures/item/zoomers_armory:fixed_bone_spear").maxDamage(3200);
e.create("zoomers_armory:fixed_bone_halberd", "sword").displayName("Fixed bone Halberd").texture("zoomers_armory:textures/item/zoomers_armory:fixed_bone_halberd").maxDamage(3840);
e.create("zoomers_armory:fixed_bone_buckler", "shield").displayName("Fixed_bone Buckler").texture("zoomers_armory:textures/item/zoomers_armory:fixed_bone_buckler").maxDamage(2880);
e.create("zoomers_armory:fixed_bone_heater", "shield").displayName("Fixed_bone Heater").texture("zoomers_armory:textures/item/zoomers_armory:fixed_bone_heater").maxDamage(3840);
e.create("zoomers_armory:fixed_bone_tower", "shield").displayName("Fixed_bone Tower").texture("zoomers_armory:textures/item/zoomers_armory:fixed_bone_tower").maxDamage(4800);
e.create("zoomers_armory:fusion_dagger", "sword").displayName("Fusion Dagger").texture("zoomers_armory:textures/item/zoomers_armory:fusion_dagger").maxDamage(3060);
e.create("zoomers_armory:fusion_shortsword", "sword").displayName("Fusion Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:fusion_shortsword").maxDamage(3400);
e.create("zoomers_armory:fusion_heavysword", "sword").displayName("Fusion Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:fusion_heavysword").maxDamage(5100);
e.create("zoomers_armory:fusion_cutlass", "sword").displayName("Fusion Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:fusion_cutlass").maxDamage(4080);
e.create("zoomers_armory:fusion_mace", "sword").displayName("Fusion Mace").texture("zoomers_armory:textures/item/zoomers_armory:fusion_mace").maxDamage(4080);
e.create("zoomers_armory:fusion_heavymace", "sword").displayName("Fusion Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:fusion_heavymace").maxDamage(5100);
e.create("zoomers_armory:fusion_warhammer", "sword").displayName("Fusion Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:fusion_warhammer").maxDamage(6120);
e.create("zoomers_armory:fusion_spear", "sword").displayName("Fusion Spear").texture("zoomers_armory:textures/item/zoomers_armory:fusion_spear").maxDamage(3400);
e.create("zoomers_armory:fusion_halberd", "sword").displayName("Fusion Halberd").texture("zoomers_armory:textures/item/zoomers_armory:fusion_halberd").maxDamage(4080);
e.create("zoomers_armory:fusion_buckler", "shield").displayName("Fusion Buckler").texture("zoomers_armory:textures/item/zoomers_armory:fusion_buckler").maxDamage(3060);
e.create("zoomers_armory:fusion_heater", "shield").displayName("Fusion Heater").texture("zoomers_armory:textures/item/zoomers_armory:fusion_heater").maxDamage(4080);
e.create("zoomers_armory:fusion_tower", "shield").displayName("Fusion Tower").texture("zoomers_armory:textures/item/zoomers_armory:fusion_tower").maxDamage(5100);
e.create("zoomers_armory:aberythe_dagger", "sword").displayName("Aberythe Dagger").texture("zoomers_armory:textures/item/zoomers_armory:aberythe_dagger").maxDamage(3240);
e.create("zoomers_armory:aberythe_shortsword", "sword").displayName("Aberythe Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:aberythe_shortsword").maxDamage(3600);
e.create("zoomers_armory:aberythe_heavysword", "sword").displayName("Aberythe Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:aberythe_heavysword").maxDamage(5400);
e.create("zoomers_armory:aberythe_cutlass", "sword").displayName("Aberythe Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:aberythe_cutlass").maxDamage(4320);
e.create("zoomers_armory:aberythe_mace", "sword").displayName("Aberythe Mace").texture("zoomers_armory:textures/item/zoomers_armory:aberythe_mace").maxDamage(4320);
e.create("zoomers_armory:aberythe_heavymace", "sword").displayName("Aberythe Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:aberythe_heavymace").maxDamage(5400);
e.create("zoomers_armory:aberythe_warhammer", "sword").displayName("Aberythe Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:aberythe_warhammer").maxDamage(6480);
e.create("zoomers_armory:aberythe_spear", "sword").displayName("Aberythe Spear").texture("zoomers_armory:textures/item/zoomers_armory:aberythe_spear").maxDamage(3600);
e.create("zoomers_armory:aberythe_halberd", "sword").displayName("Aberythe Halberd").texture("zoomers_armory:textures/item/zoomers_armory:aberythe_halberd").maxDamage(4320);
e.create("zoomers_armory:aberythe_buckler", "shield").displayName("Aberythe Buckler").texture("zoomers_armory:textures/item/zoomers_armory:aberythe_buckler").maxDamage(3240);
e.create("zoomers_armory:aberythe_heater", "shield").displayName("Aberythe Heater").texture("zoomers_armory:textures/item/zoomers_armory:aberythe_heater").maxDamage(4320);
e.create("zoomers_armory:aberythe_tower", "shield").displayName("Aberythe Tower").texture("zoomers_armory:textures/item/zoomers_armory:aberythe_tower").maxDamage(5400);
e.create("zoomers_armory:ignisithe_dagger", "sword").displayName("Ignisithe Dagger").texture("zoomers_armory:textures/item/zoomers_armory:ignisithe_dagger").maxDamage(3420);
e.create("zoomers_armory:ignisithe_shortsword", "sword").displayName("Ignisithe Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:ignisithe_shortsword").maxDamage(3800);
e.create("zoomers_armory:ignisithe_heavysword", "sword").displayName("Ignisithe Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:ignisithe_heavysword").maxDamage(5700);
e.create("zoomers_armory:ignisithe_cutlass", "sword").displayName("Ignisithe Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:ignisithe_cutlass").maxDamage(4560);
e.create("zoomers_armory:ignisithe_mace", "sword").displayName("Ignisithe Mace").texture("zoomers_armory:textures/item/zoomers_armory:ignisithe_mace").maxDamage(4560);
e.create("zoomers_armory:ignisithe_heavymace", "sword").displayName("Ignisithe Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:ignisithe_heavymace").maxDamage(5700);
e.create("zoomers_armory:ignisithe_warhammer", "sword").displayName("Ignisithe Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:ignisithe_warhammer").maxDamage(6840);
e.create("zoomers_armory:ignisithe_spear", "sword").displayName("Ignisithe Spear").texture("zoomers_armory:textures/item/zoomers_armory:ignisithe_spear").maxDamage(3800);
e.create("zoomers_armory:ignisithe_halberd", "sword").displayName("Ignisithe Halberd").texture("zoomers_armory:textures/item/zoomers_armory:ignisithe_halberd").maxDamage(4560);
e.create("zoomers_armory:ignisithe_buckler", "shield").displayName("Ignisithe Buckler").texture("zoomers_armory:textures/item/zoomers_armory:ignisithe_buckler").maxDamage(3420);
e.create("zoomers_armory:ignisithe_heater", "shield").displayName("Ignisithe Heater").texture("zoomers_armory:textures/item/zoomers_armory:ignisithe_heater").maxDamage(4560);
e.create("zoomers_armory:ignisithe_tower", "shield").displayName("Ignisithe Tower").texture("zoomers_armory:textures/item/zoomers_armory:ignisithe_tower").maxDamage(5700);
e.create("zoomers_armory:glacerythe_dagger", "sword").displayName("Glacerythe Dagger").texture("zoomers_armory:textures/item/zoomers_armory:glacerythe_dagger").maxDamage(3600);
e.create("zoomers_armory:glacerythe_shortsword", "sword").displayName("Glacerythe Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:glacerythe_shortsword").maxDamage(4000);
e.create("zoomers_armory:glacerythe_heavysword", "sword").displayName("Glacerythe Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:glacerythe_heavysword").maxDamage(6000);
e.create("zoomers_armory:glacerythe_cutlass", "sword").displayName("Glacerythe Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:glacerythe_cutlass").maxDamage(4800);
e.create("zoomers_armory:glacerythe_mace", "sword").displayName("Glacerythe Mace").texture("zoomers_armory:textures/item/zoomers_armory:glacerythe_mace").maxDamage(4800);
e.create("zoomers_armory:glacerythe_heavymace", "sword").displayName("Glacerythe Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:glacerythe_heavymace").maxDamage(6000);
e.create("zoomers_armory:glacerythe_warhammer", "sword").displayName("Glacerythe Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:glacerythe_warhammer").maxDamage(7200);
e.create("zoomers_armory:glacerythe_spear", "sword").displayName("Glacerythe Spear").texture("zoomers_armory:textures/item/zoomers_armory:glacerythe_spear").maxDamage(4000);
e.create("zoomers_armory:glacerythe_halberd", "sword").displayName("Glacerythe Halberd").texture("zoomers_armory:textures/item/zoomers_armory:glacerythe_halberd").maxDamage(4800);
e.create("zoomers_armory:glacerythe_buckler", "shield").displayName("Glacerythe Buckler").texture("zoomers_armory:textures/item/zoomers_armory:glacerythe_buckler").maxDamage(3600);
e.create("zoomers_armory:glacerythe_heater", "shield").displayName("Glacerythe Heater").texture("zoomers_armory:textures/item/zoomers_armory:glacerythe_heater").maxDamage(4800);
e.create("zoomers_armory:glacerythe_tower", "shield").displayName("Glacerythe Tower").texture("zoomers_armory:textures/item/zoomers_armory:glacerythe_tower").maxDamage(6000);
e.create("zoomers_armory:garnite_dagger", "sword").displayName("Garnite Dagger").texture("zoomers_armory:textures/item/zoomers_armory:garnite_dagger").maxDamage(3780);
e.create("zoomers_armory:garnite_shortsword", "sword").displayName("Garnite Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:garnite_shortsword").maxDamage(4200);
e.create("zoomers_armory:garnite_heavysword", "sword").displayName("Garnite Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:garnite_heavysword").maxDamage(6300);
e.create("zoomers_armory:garnite_cutlass", "sword").displayName("Garnite Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:garnite_cutlass").maxDamage(5040);
e.create("zoomers_armory:garnite_mace", "sword").displayName("Garnite Mace").texture("zoomers_armory:textures/item/zoomers_armory:garnite_mace").maxDamage(5040);
e.create("zoomers_armory:garnite_heavymace", "sword").displayName("Garnite Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:garnite_heavymace").maxDamage(6300);
e.create("zoomers_armory:garnite_warhammer", "sword").displayName("Garnite Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:garnite_warhammer").maxDamage(7560);
e.create("zoomers_armory:garnite_spear", "sword").displayName("Garnite Spear").texture("zoomers_armory:textures/item/zoomers_armory:garnite_spear").maxDamage(4200);
e.create("zoomers_armory:garnite_halberd", "sword").displayName("Garnite Halberd").texture("zoomers_armory:textures/item/zoomers_armory:garnite_halberd").maxDamage(5040);
e.create("zoomers_armory:garnite_buckler", "shield").displayName("Garnite Buckler").texture("zoomers_armory:textures/item/zoomers_armory:garnite_buckler").maxDamage(3780);
e.create("zoomers_armory:garnite_heater", "shield").displayName("Garnite Heater").texture("zoomers_armory:textures/item/zoomers_armory:garnite_heater").maxDamage(5040);
e.create("zoomers_armory:garnite_tower", "shield").displayName("Garnite Tower").texture("zoomers_armory:textures/item/zoomers_armory:garnite_tower").maxDamage(6300);
e.create("zoomers_armory:phantom_dagger", "sword").displayName("Phantom Dagger").texture("zoomers_armory:textures/item/zoomers_armory:phantom_dagger").maxDamage(3960);
e.create("zoomers_armory:phantom_shortsword", "sword").displayName("Phantom Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:phantom_shortsword").maxDamage(4400);
e.create("zoomers_armory:phantom_heavysword", "sword").displayName("Phantom Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:phantom_heavysword").maxDamage(6600);
e.create("zoomers_armory:phantom_cutlass", "sword").displayName("Phantom Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:phantom_cutlass").maxDamage(5280);
e.create("zoomers_armory:phantom_mace", "sword").displayName("Phantom Mace").texture("zoomers_armory:textures/item/zoomers_armory:phantom_mace").maxDamage(5280);
e.create("zoomers_armory:phantom_heavymace", "sword").displayName("Phantom Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:phantom_heavymace").maxDamage(6600);
e.create("zoomers_armory:phantom_warhammer", "sword").displayName("Phantom Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:phantom_warhammer").maxDamage(7920);
e.create("zoomers_armory:phantom_spear", "sword").displayName("Phantom Spear").texture("zoomers_armory:textures/item/zoomers_armory:phantom_spear").maxDamage(4400);
e.create("zoomers_armory:phantom_halberd", "sword").displayName("Phantom Halberd").texture("zoomers_armory:textures/item/zoomers_armory:phantom_halberd").maxDamage(5280);
e.create("zoomers_armory:phantom_buckler", "shield").displayName("Phantom Buckler").texture("zoomers_armory:textures/item/zoomers_armory:phantom_buckler").maxDamage(3960);
e.create("zoomers_armory:phantom_heater", "shield").displayName("Phantom Heater").texture("zoomers_armory:textures/item/zoomers_armory:phantom_heater").maxDamage(5280);
e.create("zoomers_armory:phantom_tower", "shield").displayName("Phantom Tower").texture("zoomers_armory:textures/item/zoomers_armory:phantom_tower").maxDamage(6600);
e.create("zoomers_armory:unorithe_dagger", "sword").displayName("Unorithe Dagger").texture("zoomers_armory:textures/item/zoomers_armory:unorithe_dagger").maxDamage(4140);
e.create("zoomers_armory:unorithe_shortsword", "sword").displayName("Unorithe Shortsword").texture("zoomers_armory:textures/item/zoomers_armory:unorithe_shortsword").maxDamage(4600);
e.create("zoomers_armory:unorithe_heavysword", "sword").displayName("Unorithe Heavysword").texture("zoomers_armory:textures/item/zoomers_armory:unorithe_heavysword").maxDamage(6900);
e.create("zoomers_armory:unorithe_cutlass", "sword").displayName("Unorithe Cutlass").texture("zoomers_armory:textures/item/zoomers_armory:unorithe_cutlass").maxDamage(5520);
e.create("zoomers_armory:unorithe_mace", "sword").displayName("Unorithe Mace").texture("zoomers_armory:textures/item/zoomers_armory:unorithe_mace").maxDamage(5520);
e.create("zoomers_armory:unorithe_heavymace", "sword").displayName("Unorithe Heavymace").texture("zoomers_armory:textures/item/zoomers_armory:unorithe_heavymace").maxDamage(6900);
e.create("zoomers_armory:unorithe_warhammer", "sword").displayName("Unorithe Warhammer").texture("zoomers_armory:textures/item/zoomers_armory:unorithe_warhammer").maxDamage(8280);
e.create("zoomers_armory:unorithe_spear", "sword").displayName("Unorithe Spear").texture("zoomers_armory:textures/item/zoomers_armory:unorithe_spear").maxDamage(4600);
e.create("zoomers_armory:unorithe_halberd", "sword").displayName("Unorithe Halberd").texture("zoomers_armory:textures/item/zoomers_armory:unorithe_halberd").maxDamage(5520);
e.create("zoomers_armory:unorithe_buckler", "shield").displayName("Unorithe Buckler").texture("zoomers_armory:textures/item/zoomers_armory:unorithe_buckler").maxDamage(4140);
e.create("zoomers_armory:unorithe_heater", "shield").displayName("Unorithe Heater").texture("zoomers_armory:textures/item/zoomers_armory:unorithe_heater").maxDamage(5520);
e.create("zoomers_armory:unorithe_tower", "shield").displayName("Unorithe Tower").texture("zoomers_armory:textures/item/zoomers_armory:unorithe_tower").maxDamage(6900);
});
