StartupEvents.registry('item', event => {

    event.create('tier_1_armor_power_up')
        .maxStackSize(64)
        .displayName('§lTier 1 Armor Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2 Armor')

    event.create('tier_2_armor_power_up')
        .maxStackSize(64)
        .displayName('§lTier 2 Armor Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+4 Armor')

    event.create('tier_3_armor_power_up')
        .maxStackSize(64)
        .displayName('§lTier 3 Armor Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+6 Armor')

    event.create('tier_4_armor_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 4 Armor Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+8 Armor')

    event.create('tier_5_armor_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 5 Armor Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+12 Armor')

    event.create('tier_6_armor_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 6 Armor Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+18 Armor')

    event.create('tier_7_armor_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 7 Armor Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+25 Armor')

    event.create('tier_8_armor_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 8 Armor Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+32 Armor')

    event.create('tier_9_armor_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 9 Armor Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+40 Armor')

    event.create('tier_10_armor_power_up')
        .maxStackSize(64)
        .displayName('§5§lTier 10 Armor Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+75 Armor')

    event.create('tier_1_armor_toughness_power_up')
        .maxStackSize(64)
        .displayName('§lTier 1 Armor Toughness Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.25 Armor Toughness')

    event.create('tier_2_armor_toughness_power_up')
        .maxStackSize(64)
        .displayName('§lTier 2 Armor Toughness Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.5 Armor Toughness')

    event.create('tier_3_armor_toughness_power_up')
        .maxStackSize(64)
        .displayName('§lTier 3 Armor Toughness Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.75 Armor Toughness')

    event.create('tier_4_armor_toughness_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 4 Armor Toughness Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2.0 Armor Toughness')

    event.create('tier_5_armor_toughness_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 5 Armor Toughness Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+4.0 Armor Toughness')

    event.create('tier_6_armor_toughness_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 6 Armor Toughness Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+5.0 Armor Toughness')

    event.create('tier_7_armor_toughness_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 7 Armor Toughness Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+6.0 Armor Toughness')

    event.create('tier_8_armor_toughness_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 8 Armor Toughness Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+7.0 Armor Toughness')

    event.create('tier_9_armor_toughness_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 9 Armor Toughness Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+8.0 Armor Toughness')

    event.create('tier_10_armor_toughness_power_up')
        .maxStackSize(64)
        .displayName('§5§lTier 10 Armor Toughness Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+10.0 Armor Toughness')

    event.create('tier_1_armor_pierce_power_up')
        .maxStackSize(64)
        .displayName('§lTier 1 Armor Pierce Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.25 Armor Pierce')

    event.create('tier_2_armor_pierce_power_up')
        .maxStackSize(64)
        .displayName('§lTier 2 Armor Pierce Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.5 Armor Pierce')

    event.create('tier_3_armor_pierce_power_up')
        .maxStackSize(64)
        .displayName('§lTier 3 Armor Pierce Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.75 Armor Pierce')

    event.create('tier_4_armor_pierce_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 4 Armor Pierce Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2.0 Armor Pierce')

    event.create('tier_5_armor_pierce_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 5 Armor Pierce Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+4.0 Armor Pierce')

    event.create('tier_6_armor_pierce_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 6 Armor Pierce Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+5.0 Armor Pierce')

    event.create('tier_7_armor_pierce_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 7 Armor Pierce Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+6.0 Armor Pierce')

    event.create('tier_8_armor_pierce_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 8 Armor Pierce Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+7.0 Armor Pierce')

    event.create('tier_9_armor_pierce_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 9 Armor Pierce Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+8.0 Armor Pierce')

    event.create('tier_10_armor_pierce_power_up')
        .maxStackSize(64)
        .displayName('§5§lTier 10 Armor Pierce Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+10.0 Armor Pierce')

    event.create('tier_1_armor_shred_power_up')
        .maxStackSize(64)
        .displayName('§lTier 1 Armor Shred Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+0.1% Armor Shred')

    event.create('tier_2_armor_shred_power_up')
        .maxStackSize(64)
        .displayName('§lTier 2 Armor Shred Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+0.2% Armor Shred')

    event.create('tier_3_armor_shred_power_up')
        .maxStackSize(64)
        .displayName('§lTier 3 Armor Shred Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+0.4% Armor Shred')

    event.create('tier_4_armor_shred_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 4 Armor Shred Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+0.8% Armor Shred')

    event.create('tier_5_armor_shred_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 5 Armor Shred Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.0% Armor Shred')

    event.create('tier_6_armor_shred_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 6 Armor Shred Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.2% Armor Shred')

    event.create('tier_7_armor_shred_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 7 Armor Shred Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.4% Armor Shred')

    event.create('tier_8_armor_shred_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 8 Armor Shred Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.6% Armor Shred')

    event.create('tier_9_armor_shred_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 9 Armor Shred Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.8% Armor Shred')

    event.create('tier_10_armor_shred_power_up')
        .maxStackSize(64)
        .displayName('§5§lTier 10 Armor Shred Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2.0% Armor Shred')

    event.create('tier_1_cooldown_reduction_power_up')
        .maxStackSize(64)
        .displayName('§lTier 1 Cooldown Reduction Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+3.75% Cooldown Reduction')

    event.create('tier_2_cooldown_reduction_power_up')
        .maxStackSize(64)
        .displayName('§lTier 2 Cooldown Reduction Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+4.0% Cooldown Reduction')

    event.create('tier_3_cooldown_reduction_power_up')
        .maxStackSize(64)
        .displayName('§lTier 3 Cooldown Reduction Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+4.25% Cooldown Reduction')

    event.create('tier_4_cooldown_reduction_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 4 Cooldown Reduction Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+4.5% Cooldown Reduction')

    event.create('tier_5_cooldown_reduction_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 5 Cooldown Reduction Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+5.0% Cooldown Reduction')

    event.create('tier_6_cooldown_reduction_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 6 Cooldown Reduction Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+6.0% Cooldown Reduction')

    event.create('tier_7_cooldown_reduction_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 7 Cooldown Reduction Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+7.0% Cooldown Reduction')

    event.create('tier_8_cooldown_reduction_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 8 Cooldown Reduction Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+8.0% Cooldown Reduction')

    event.create('tier_9_cooldown_reduction_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 9 Cooldown Reduction Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+9.0% Cooldown Reduction')

    event.create('tier_10_cooldown_reduction_power_up')
        .maxStackSize(64)
        .displayName('§5§lTier 10 Cooldown Reduction Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+12.5% Cooldown Reduction')

    event.create('tier_1_crit_chance_power_up')
        .maxStackSize(64)
        .displayName('§lTier 1 Critical Chance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.0% Critical Chance')

    event.create('tier_2_crit_chance_power_up')
        .maxStackSize(64)
        .displayName('§lTier 2 Critical Chance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.25% Critical Chance')

    event.create('tier_3_crit_chance_power_up')
        .maxStackSize(64)
        .displayName('§lTier 3 Critical Chance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.5% Critical Chance')

    event.create('tier_4_crit_chance_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 4 Critical Chance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.75% Critical Chance')

    event.create('tier_5_crit_chance_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 5 Critical Chance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2.0% Critical Chance')

    event.create('tier_6_crit_chance_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 6 Critical Chance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2.5% Critical Chance')

    event.create('tier_7_crit_chance_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 7 Critical Chance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+3.0% Critical Chance')

    event.create('tier_8_crit_chance_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 8 Critical Chance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+3.5% Critical Chance')

    event.create('tier_9_crit_chance_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 9 Critical Chance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+4.0% Critical Chance')

    event.create('tier_10_crit_chance_power_up')
        .maxStackSize(64)
        .displayName('§5§lTier 10 Critical Chance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+5.0% Critical Chance')

    event.create('tier_1_crit_damage_power_up')
        .maxStackSize(64)
        .displayName('§lTier 1 Critical Damage Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.0% Critical Damage')

    event.create('tier_2_crit_damage_power_up')
        .maxStackSize(64)
        .displayName('§lTier 2 Critical Damage Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.25% Critical Damage')

    event.create('tier_3_crit_damage_power_up')
        .maxStackSize(64)
        .displayName('§lTier 3 Critical Damage Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.5% Critical Damage')

    event.create('tier_4_crit_damage_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 4 Critical Damage Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.75% Critical Damage')

    event.create('tier_5_crit_damage_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 5 Critical Damage Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2.0% Critical Damage')

    event.create('tier_6_crit_damage_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 6 Critical Damage Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2.5% Critical Damage')

    event.create('tier_7_crit_damage_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 7 Critical Damage Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+3.0% Critical Damage')

    event.create('tier_8_crit_damage_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 8 Critical Damage Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+3.5% Critical Damage')

    event.create('tier_9_crit_damage_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 9 Critical Damage Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+4.0% Critical Damage')

    event.create('tier_10_crit_damage_power_up')
        .maxStackSize(64)
        .displayName('§5§lTier 10 Critical Damage Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+5.0% Critical Damage')

    event.create('tier_1_health_boost_power_up')
        .maxStackSize(64)
        .displayName('§lTier 1 Health Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+4 Health Boost')

    event.create('tier_2_health_boost_power_up')
        .maxStackSize(64)
        .displayName('§lTier 2 Health Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+8 Health Boost')

    event.create('tier_3_health_boost_power_up')
        .maxStackSize(64)
        .displayName('§lTier 3 Health Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+12 Health Boost')

    event.create('tier_4_health_boost_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 4 Health Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+16 Health Boost')

    event.create('tier_5_health_boost_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 5 Health Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+32 Health Boost')

    event.create('tier_6_health_boost_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 6 Health Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+48 Health Boost')

    event.create('tier_7_health_boost_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 7 Health Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+60 Health Boost')

    event.create('tier_8_health_boost_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 8 Health Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+80 Health Boost')

    event.create('tier_9_health_boost_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 9 Health Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+100 Health Boost')

    event.create('tier_10_health_boost_power_up')
        .maxStackSize(64)
        .displayName('§5§lTier 10 Health Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+120 Health Boost')

    event.create('tier_1_knockback_resistance_power_up')
        .maxStackSize(64)
        .displayName('§lTier 1 Knockback Resistance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.0% Knockback Resistance')

    event.create('tier_2_knockback_resistance_power_up')
        .maxStackSize(64)
        .displayName('§lTier 2 Knockback Resistance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.25% Knockback Resistance')

    event.create('tier_3_knockback_resistance_power_up')
        .maxStackSize(64)
        .displayName('§lTier 3 Knockback Resistance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.5% Knockback Resistance')

    event.create('tier_4_knockback_resistance_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 4 Knockback Resistance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.75% Knockback Resistance')

    event.create('tier_5_knockback_resistance_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 5 Knockback Resistance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2.0% Knockback Resistance')

    event.create('tier_6_knockback_resistance_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 6 Knockback Resistance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2.5% Knockback Resistance')

    event.create('tier_7_knockback_resistance_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 7 Knockback Resistance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+3.0% Knockback Resistance')

    event.create('tier_8_knockback_resistance_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 8 Knockback Resistance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+3.5% Knockback Resistance')

    event.create('tier_9_knockback_resistance_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 9 Knockback Resistance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+4.0% Knockback Resistance')

    event.create('tier_10_knockback_resistance_power_up')
        .maxStackSize(64)
        .displayName('§5§lTier 10 Knockback Resistance Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+5.0% Knockback Resistance')

    event.create('tier_1_lung_capacity_power_up')
        .maxStackSize(64)
        .displayName('§lTier 1 Lung Capacity Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+20 Lung Capacity')

    event.create('tier_2_lung_capacity_power_up')
        .maxStackSize(64)
        .displayName('§lTier 2 Lung Capacity Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+40 Lung Capacity')

    event.create('tier_3_lung_capacity_power_up')
        .maxStackSize(64)
        .displayName('§lTier 3 Lung Capacity Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+60 Lung Capacity')

    event.create('tier_4_lung_capacity_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 4 Lung Capacity Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+80 Lung Capacity')

    event.create('tier_5_lung_capacity_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 5 Lung Capacity Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+100 Lung Capacity')

    event.create('tier_6_lung_capacity_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 6 Lung Capacity Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+120 Lung Capacity')

    event.create('tier_7_lung_capacity_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 7 Lung Capacity Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+140 Lung Capacity')

    event.create('tier_8_lung_capacity_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 8 Lung Capacity Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+160 Lung Capacity')

    event.create('tier_9_lung_capacity_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 9 Lung Capacity Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+180 Lung Capacity')

    event.create('tier_10_lung_capacity_power_up')
        .maxStackSize(64)
        .displayName('§5§lTier 10 Lung Capacity Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+240 Lung Capacity')

    event.create('tier_1_mana_boost_power_up')
        .maxStackSize(64)
        .displayName('§lTier 1 Mana Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+10 Mana Boost')

    event.create('tier_2_mana_boost_power_up')
        .maxStackSize(64)
        .displayName('§lTier 2 Mana Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+12 Mana Boost')

    event.create('tier_3_mana_boost_power_up')
        .maxStackSize(64)
        .displayName('§lTier 3 Mana Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+15 Mana Boost')

    event.create('tier_4_mana_boost_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 4 Mana Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+17 Mana Boost')

    event.create('tier_5_mana_boost_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 5 Mana Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+20 Mana Boost')

    event.create('tier_6_mana_boost_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 6 Mana Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+25 Mana Boost')

    event.create('tier_7_mana_boost_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 7 Mana Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+30 Mana Boost')

    event.create('tier_8_mana_boost_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 8 Mana Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+35 Mana Boost')

    event.create('tier_9_mana_boost_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 9 Mana Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+40 Mana Boost')

    event.create('tier_10_mana_boost_power_up')
        .maxStackSize(64)
        .displayName('§5§lTier 10 Mana Boost Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+50 Mana Boost')

    event.create('tier_1_mana_regen_power_up')
        .maxStackSize(64)
        .displayName('§lTier 1 Mana Regeneration Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.0% Mana Regeneration')

    event.create('tier_2_mana_regen_power_up')
        .maxStackSize(64)
        .displayName('§lTier 2 Mana Regeneration Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2.0% Mana Regeneration')

    event.create('tier_3_mana_regen_power_up')
        .maxStackSize(64)
        .displayName('§lTier 3 Mana Regeneration Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+4.0% Mana Regeneration')

    event.create('tier_4_mana_regen_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 4 Mana Regeneration Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+8.0% Mana Regeneration')

    event.create('tier_5_mana_regen_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 5 Mana Regeneration Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+10.0% Mana Regeneration')

    event.create('tier_6_mana_regen_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 6 Mana Regeneration Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+12.0% Mana Regeneration')

    event.create('tier_7_mana_regen_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 7 Mana Regeneration Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+14.0% Mana Regeneration')

    event.create('tier_8_mana_regen_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 8 Mana Regeneration Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+16.0% Mana Regeneration')

    event.create('tier_9_mana_regen_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 9 Mana Regeneration Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+18.0% Mana Regeneration')

    event.create('tier_10_mana_regen_power_up')
        .maxStackSize(64)
        .displayName('§5§lTier 10 Mana Regeneration Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+20.0% Mana Regeneration')

    event.create('tier_1_movement_speed_power_up')
        .maxStackSize(64)
        .displayName('§lTier 1 Movement Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.0% Movement Speed')

    event.create('tier_2_movement_speed_power_up')
        .maxStackSize(64)
        .displayName('§lTier 2 Movement Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.25% Movement Speed')

    event.create('tier_3_movement_speed_power_up')
        .maxStackSize(64)
        .displayName('§lTier 3 Movement Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.5% Movement Speed')

    event.create('tier_4_movement_speed_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 4 Movement Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.75% Movement Speed')

    event.create('tier_5_movement_speed_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 5 Movement Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2.0% Movement Speed')

    event.create('tier_6_movement_speed_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 6 Movement Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2.5% Movement Speed')

    event.create('tier_7_movement_speed_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 7 Movement Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+3.0% Movement Speed')

    event.create('tier_8_movement_speed_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 8 Movement Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+3.5% Movement Speed')

    event.create('tier_9_movement_speed_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 9 Movement Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+4.0% Movement Speed')

    event.create('tier_10_movement_speed_power_up')
        .maxStackSize(64)
        .displayName('§5§lTier 10 Movement Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+5.0% Movement Speed')

    event.create('tier_1_spell_power_power_up')
        .maxStackSize(64)
        .displayName('§lTier 1 Spell Power Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.0% Spell Power')

    event.create('tier_2_spell_power_power_up')
        .maxStackSize(64)
        .displayName('§lTier 2 Spell Power Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.25% Spell Power')

    event.create('tier_3_spell_power_power_up')
        .maxStackSize(64)
        .displayName('§lTier 3 Spell Power Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.5% Spell Power')

    event.create('tier_4_spell_power_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 4 Spell Power Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.75% Spell Power')

    event.create('tier_5_spell_power_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 5 Spell Power Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2.0% Spell Power')

    event.create('tier_6_spell_power_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 6 Spell Power Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2.5% Spell Power')

    event.create('tier_7_spell_power_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 7 Spell Power Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+3.0% Spell Power')

    event.create('tier_8_spell_power_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 8 Spell Power Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+3.5% Spell Power')

    event.create('tier_9_spell_power_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 9 Spell Power Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+4.0% Spell Power')

    event.create('tier_10_spell_power_power_up')
        .maxStackSize(64)
        .displayName('§5§lTier 10 Spell Power Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+5.0% Spell Power')

    event.create('tier_1_stamina_power_up')
        .maxStackSize(64)
        .displayName('§lTier 1 Stamina Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+0.1 Stamina')

    event.create('tier_2_stamina_power_up')
        .maxStackSize(64)
        .displayName('§lTier 2 Stamina Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+0.2 Stamina')

    event.create('tier_3_stamina_power_up')
        .maxStackSize(64)
        .displayName('§lTier 3 Stamina Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+0.4 Stamina')

    event.create('tier_4_stamina_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 4 Stamina Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+0.8 Stamina')

    event.create('tier_5_stamina_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 5 Stamina Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1 Stamina')

    event.create('tier_6_stamina_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 6 Stamina Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.2 Stamina')

    event.create('tier_7_stamina_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 7 Stamina Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.4 Stamina')

    event.create('tier_8_stamina_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 8 Stamina Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.6 Stamina')

    event.create('tier_9_stamina_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 9 Stamina Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.5 Stamina')

    event.create('tier_10_stamina_power_up')
        .maxStackSize(64)
        .displayName('§5§lTier 10 Stamina Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2.0 Stamina')

    event.create('tier_1_swim_speed_power_up')
        .maxStackSize(64)
        .displayName('§lTier 1 Swim Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+1.0% Swim Speed')

    event.create('tier_2_swim_speed_power_up')
        .maxStackSize(64)
        .displayName('§lTier 2 Swim Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+2.0% Swim Speed')

    event.create('tier_3_swim_speed_power_up')
        .maxStackSize(64)
        .displayName('§lTier 3 Swim Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+4.0% Swim Speed')

    event.create('tier_4_swim_speed_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 4 Swim Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+8.0% Swim Speed')

    event.create('tier_5_swim_speed_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 5 Swim Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+10.0% Swim Speed')

    event.create('tier_6_swim_speed_power_up')
        .maxStackSize(64)
        .displayName('§a§lTier 6 Swim Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+12.0% Swim Speed')

    event.create('tier_7_swim_speed_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 7 Swim Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+14.0% Swim Speed')

    event.create('tier_8_swim_speed_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 8 Swim Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+16.0% Swim Speed')

    event.create('tier_9_swim_speed_power_up')
        .maxStackSize(64)
        .displayName('§3§lTier 9 Swim Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+18.0% Swim Speed')

    event.create('tier_10_swim_speed_power_up')
        .maxStackSize(64)
        .displayName('§5§lTier 10 Swim Speed Power Up')
        .tooltip("§9Apply on armor piece with a template to gain")
        .tooltip('+20.0% Swim Speed')
});
